variable "sql_server_name" {}
variable "rg_name" {}
variable "location" {}
variable "admin_username" {}
variable "admin_password" {}
variable "tags" {}
variable "audit_storage_endpoint" {}
variable "audit_storage_account_access_key" {}
variable "audit_retention_in_days" {}
